# Generated by Django 3.1 on 2020-08-14 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iletisimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('telefon', models.CharField(max_length=10, verbose_name='Telefon')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('konu', models.TextField(verbose_name='Konu')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('gonderi_tar', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gönderim Tarihi')),
                ('okunma_tar', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
            ],
        ),
    ]
