# Generated by Django 3.1 on 2020-08-18 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=100)),
                ('favorite_lenses', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
